name: "Build 🔨"

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches: [ main ]

jobs:
  build:
    name: "Build 🔨"
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        scheme:
          - "Swiftfin"
          - "Swiftfin tvOS"

    runs-on: macos-15

    env:
      XCODE_VERSION: "16.4"
      IOS_VERSION: "18"
      TVOS_VERSION: "18"
      TVOS_SIMULATOR: "Apple TV 4K (3rd generation)"
      IPHONE_SIMULATOR: "iPhone 16 Pro"

    steps:    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SwiftGen
        run: brew install swiftgen

      - name: Set Xcode Version
        run: sudo xcode-select -s "/Applications/Xcode_${{ env.XCODE_VERSION }}.app"

      - name: Print Swift version
        run: swift --version

      - name: Cache Carthage
        uses: actions/cache@v4
        id: carthage-cache
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: ${{ runner.os }}-carthage-

      - name: Update Carthage
        run: carthage update --use-xcframeworks --cache-builds

      # FIXME: caches would keep failed compiles?

      # - name: Cache Swift packages
      #   uses: actions/cache@v4
      #   with:
      #     path: PackageCache
      #     key: ${{ runner.os }}-${{ matrix.scheme }}-spm-${{ hashFiles('**/Package.resolved') }}
      #     restore-keys: ${{ runner.os }}-${{ matrix.scheme }}-spm-

      - name: Set Simulator
        id: set_simulator
        run: |
          set -e
          if [[ "${{ matrix.scheme }}" == "Swiftfin tvOS" ]]; then
            simulator_id=$(xcrun simctl list devices available | grep -A 1000 -- "-- tvOS ${{ env.TVOS_SIMULATOR }}" | grep -m 1 "${{ env.TVOS_SIMULATOR }}" | awk -F '[()]' '{print $2}')
            echo "Latest tvOS Device: $simulator_id"
          else
            simulator_id=$(xcrun simctl list devices available | grep -A 1000 -- "-- iOS ${{ env.IOS_VERSION }}" | grep -m 1 "${{ env.IPHONE_SIMULATOR }}" | awk -F '[()]' '{print $2}')
            echo "Latest iOS Device: $simulator_id"
          fi

          if [ -z "$simulator_id" ]; then
            echo "::error::Could not find a suitable simulator."
            exit 1
          fi
          echo "simulator_id=$simulator_id" >> $GITHUB_OUTPUT

      - name: Build
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 60
          command: |
            xcodebuild build -project "Swiftfin.xcodeproj" \
            -scheme "${{ matrix.scheme }}" \
            -destination "id=${{ steps.set_simulator.outputs.simulator_id }}" \
            -clonedSourcePackagesDirPath PackageCache \
            -skipMacroValidation \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO