name: "Build 🔨"

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches: [ main ]

jobs:
  build:
    name: "Build 🔨"
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        scheme:
          - "Swiftfin"
          - "Swiftfin tvOS"

    runs-on: macos-15

    env:
      XCODE_VERSION: "16.4"
      IOS_VERSION: "18"
      TVOS_VERSION: "18"
      IPHONE_VERSION: "16"

    steps:    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SwiftGen
        run: brew install swiftgen

      - name: Set Xcode Version
        run: sudo xcode-select -s "/Applications/Xcode_${{ env.XCODE_VERSION }}.app"

      - name: Print Swift version
        run: swift --version

      - name: Cache Carthage
        uses: actions/cache@v4
        id: carthage-cache
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: ${{ runner.os }}-carthage-

      - name: Update Carthage
        run: carthage update --use-xcframeworks --cache-builds

      # FIXME: caches would keep failed compiles?

      # - name: Cache Swift packages
      #   uses: actions/cache@v4
      #   with:
      #     path: PackageCache
      #     key: ${{ runner.os }}-${{ matrix.scheme }}-spm-${{ hashFiles('**/Package.resolved') }}
      #     restore-keys: ${{ runner.os }}-${{ matrix.scheme }}-spm-

      - name: Set Simulator
        id: set_simulator
        run: |
          if [[ "${{ matrix.scheme }}" == "Swiftfin tvOS" ]]; then
            latest_sdk=$(xcrun simctl list runtimes tvOS | grep "tvOS ${{ env.TVOS_VERSION }}" | awk '{print $NF}' | sort -V | tail -n 1)
            latest_device=$(xcrun simctl list devices | grep "tvOS $latest_sdk" | awk -F'[()]' '{for(i=2;i<=NF;i+=2) print $i}' | head -n 1)
          else
            latest_sdk=$(xcrun simctl list runtimes iOS | grep "iOS ${{ env.IOS_VERSION }}" | awk '{print $NF}' | sort -V | tail -n 1)
            latest_device=$(xcrun simctl list devices | grep "iOS $latest_sdk" | grep "iPhone ${{ env.IPHONE_VERSION }}" | awk -F'[()]' '{for(i=2;i<=NF;i+=2) print $i}' | head -n 1)
          fi
          echo "latest_device=$latest_device" >> $GITHUB_OUTPUT

      - name: Build
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 60
          command: |
            xcodebuild build -project "Swiftfin.xcodeproj" \
            -scheme "${{ matrix.scheme }}" \
            -destination "id=${{ steps.set_simulator.outputs.latest_device }}" \
            -clonedSourcePackagesDirPath PackageCache \
            -skipMacroValidation \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
